/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        electrical = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        carpenter = new javax.swing.JTextPane();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        HouseHold = new javax.swing.JTextPane();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        anyother = new javax.swing.JTextPane();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 43)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Report");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 20, 160, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(50, 80, 700, 10);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(" X");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(784, 10, 20, 20);

        jScrollPane1.setViewportView(electrical);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 140, 250, 50);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 102, 2));
        jLabel4.setText(" Issues:");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 90, 100, 30);

        jRadioButton1.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("In progress");
        jRadioButton1.setEnabled(false);
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(440, 150, 93, 23);

        jRadioButton2.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Opened");
        jRadioButton2.setEnabled(false);
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(330, 150, 63, 23);

        jRadioButton3.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Completed");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton3.setEnabled(false);
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(560, 150, 77, 23);

        jScrollPane3.setViewportView(carpenter);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(40, 220, 250, 50);

        jRadioButton4.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("In progress");
        jRadioButton4.setEnabled(false);
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(440, 230, 81, 23);

        jRadioButton5.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("Opened");
        jRadioButton5.setEnabled(false);
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(330, 230, 63, 23);

        jRadioButton6.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Completed");
        jRadioButton6.setEnabled(false);
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(560, 230, 77, 23);

        jScrollPane2.setViewportView(HouseHold);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 302, 250, 50);

        jRadioButton7.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setText("In progress");
        jRadioButton7.setEnabled(false);
        jPanel1.add(jRadioButton7);
        jRadioButton7.setBounds(440, 310, 81, 23);

        jRadioButton8.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setSelected(true);
        jRadioButton8.setText("Opened");
        jRadioButton8.setEnabled(false);
        jPanel1.add(jRadioButton8);
        jRadioButton8.setBounds(330, 310, 63, 23);

        jRadioButton9.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setText("Completed");
        jRadioButton9.setEnabled(false);
        jPanel1.add(jRadioButton9);
        jRadioButton9.setBounds(560, 310, 77, 23);

        jScrollPane4.setViewportView(anyother);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(40, 382, 250, 50);

        jRadioButton10.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup4.add(jRadioButton10);
        jRadioButton10.setText("In progress");
        jRadioButton10.setEnabled(false);
        jPanel1.add(jRadioButton10);
        jRadioButton10.setBounds(440, 390, 81, 23);

        jRadioButton11.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup4.add(jRadioButton11);
        jRadioButton11.setSelected(true);
        jRadioButton11.setText("Opened");
        jRadioButton11.setEnabled(false);
        jPanel1.add(jRadioButton11);
        jRadioButton11.setBounds(330, 390, 63, 23);

        jRadioButton12.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup4.add(jRadioButton12);
        jRadioButton12.setText("Completed");
        jRadioButton12.setEnabled(false);
        jPanel1.add(jRadioButton12);
        jRadioButton12.setBounds(560, 390, 77, 23);

        jButton1.setText("Payment of Service");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 450, 190, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 102, 2));
        jLabel5.setText("  Work Status");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 90, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\vintage-in-pastel-soft-tone-color-background-vector-15428359.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
System.exit(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
payment p=new payment();
p.setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane HouseHold;
    private javax.swing.JTextPane anyother;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextPane carpenter;
    private javax.swing.JTextPane electrical;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
